require("core.colorscheme")
require("core.keymaps")
require("core.options")
require("plugin-manager")

require("plugins.alpha-nvim")
require("plugins.competitest")
require("plugins.lualine")
require("plugins.noice")
require("plugins.nvim-tree")
require("plugins.telescope")
